"""Pydantic schemas for tool profiles generated by ProfilerAgent."""

from pydantic import BaseModel


class ToolProfile(BaseModel):
    slug: str
    name: str
    license: str
    domains: list[str]
    autonomy_level: str
    autonomy_rationale: str
    interface: str
    resource_requirements: str
    last_commit: str | None
    stars: int | None
    open_issues: int | None
    pricing_note: str
    key_limitations: list[str]
    github_url: str | None
    paper_url: str | None
    project_url: str | None
    source_ids: list[int]


class RejectedProfile(BaseModel):
    slug: str
    name: str
    rejection_reason: str
